[wip] feat: ledger import add new address button
ArdentHQ/arkvault pull request #134
Opened 2022-08-16 18:06 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/2gnzkpp

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-08-17 11:18 UTC, samharperpittam requested changes
Very minor issue on this.

On this import ledger page
<img width="783" alt="image" src="https://user-images.githubusercontent.com/44671015/185105517-8c904f8f-3a35-42b2-8ff0-626c25f8170f.png">

If you uncheck all the addresses by using the checkbox in the table header, and then select "Add new Address" , all of the checkboxes get enabled again by default. Is it possible to change this so only the newly added address is enabled by default?

2022-08-17 14:34 UTC, alfonsobries commented
@samharperpittam fixed ✅

2022-08-18 09:23 UTC, samharperpittam approved these changes

2022-08-19 06:36 UTC, dated approved these changes

2022-08-19 08:24 UTC, goga-m approved these changes

2022-08-19 08:24 UTC, merged