[wip] feat: deeplink message sign
ArdentHQ/arkvault pull request #138
Opened 2022-08-18 16:48 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/2p89rtg

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-08-19 08:30 UTC, ItsANameToo commented
@alfonsobries I changed the base to `feat/message-sign-deeplinking`, can you open any additional PRs against that branch so we combine it all in there before merging it into develop upon completion?

2022-08-19 10:59 UTC, dated commented on src/app/hooks/use-search-parameters-validation.ts
> +			},
```suggestion
			path: ({ profile, parameters }: PathProperties) =>
				`${generatePath(ProfilePaths.SignMessage, {
					profileId: profile.id(),
				})}?${parameters.toString()}`,
```

When deeplinking we always use the paths without wallet context.

2022-08-24 12:25 UTC, samharperpittam requested changes
- Wallet with 0 balance can't sign a message, found by @dated 
<img width="864" alt="image" src="https://user-images.githubusercontent.com/44671015/186417512-8dcf3f96-3634-49d4-a169-7133cb6b3366.png">


- ~When trying to sign with a Ledger wallet, the following error can be found in console
`SignMessage.tsx:110 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'coinId')`~ fixed

2022-08-25 09:16 UTC, samharperpittam requested changes
~Show error if message content exceeds the allowed limit~fixed in [f2bd0a6](https://github.com/ArdentHQ/arkvault/pull/138/commits/f2bd0a65c9b88955050504e42408084041d005d6)

<img width="805" alt="image" src="https://user-images.githubusercontent.com/44671015/186626120-d1e929ae-675c-4e32-97df-3cc40e4da776.png">

2022-08-25 09:55 UTC, samharperpittam approved these changes

2022-08-30 14:02 UTC, goga-m approved these changes

2022-08-30 16:10 UTC, samharperpittam approved these changes

2022-08-30 16:11 UTC, merged