refactor: break words in ledger details
ArdentHQ/arkvault pull request #141
Opened 2022-08-19 15:54 UTC by dated

## Summary

https://app.clickup.com/t/2r7etp1

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [x] Ready to be merged

2022-08-22 12:52 UTC, samharperpittam approved these changes

2022-08-23 08:18 UTC, ItsANameToo requested changes

2022-08-23 08:24 UTC, dated commented on src/domains/message/pages/SignMessage/SignMessage.tsx
> +												<p className="whitespace-pre-line break-all">{getValues("message")}</p>
I took inspiration from https://github.com/ArdentHQ/arkvault/blob/develop/src/domains/transaction/components/TransactionDetail/TransactionMemo/TransactionMemo.tsx#L24

2022-08-23 08:28 UTC, dated commented on src/domains/message/pages/SignMessage/SignMessage.tsx
> +												<p className="whitespace-pre-line break-all">{getValues("message")}</p>
I will adjust the TransactionMemo as well in a dedicated PR.

2022-08-23 09:21 UTC, samharperpittam approved these changes

2022-08-23 10:03 UTC, ItsANameToo approved these changes

2022-08-23 10:04 UTC, merged