feat: migration banner
ArdentHQ/arkvault pull request #270
Opened 2022-12-13 16:44 UTC by alfonsobries

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-12-13 21:07 UTC, dated requested changes

2022-12-13 21:07 UTC, dated commented on src/domains/dashboard/components/Migration/MigrationBanner.tsx
> +					<PolygonMigrationBannerDark className="hidden w-full dark:block" />
```suggestion
					<Image name="PolygonMigrationBanner" useAccentColor={false} />
```

2022-12-13 21:07 UTC, dated commented on src/domains/dashboard/components/Migration/MigrationBanner.tsx
> +				<div className="max-w-2xl flex-1  py-6">
```suggestion
				<div className="max-w-2xl flex-1 py-6">
```

2022-12-13 21:07 UTC, dated commented on src/domains/dashboard/components/Migration/MigrationBanner.tsx
> +};
Can be based on the `useLink()` hook, e.g.

```ts
const { openExternal } = useLink();
```

2022-12-13 22:31 UTC, alfonsobries commented
@dated ✅

2022-12-14 00:48 UTC, dated commented
> @dated ✅

did you forget to push? :trollface:

2022-12-14 04:35 UTC, alfonsobries commented
@dated apparently yes (and also lost the haha) but just updated again

2022-12-14 09:25 UTC, ItsANameToo approved these changes

2022-12-14 11:04 UTC, samharperpittam requested changes
Header should be 18px on mobile

Design
<img width="307" alt="image" src="https://user-images.githubusercontent.com/44671015/207578823-317113ca-48ac-421a-a31b-925f625f5c5d.png">

Imp
<img width="399" alt="image" src="https://user-images.githubusercontent.com/44671015/207578757-4a627104-1060-4adf-9a96-f00850c70f53.png">

2022-12-14 11:07 UTC, samharperpittam requested changes
The text within the banner should be semi-bold

<img width="753" alt="image" src="https://user-images.githubusercontent.com/44671015/207579535-fa4c55b7-7eaa-4133-adc9-bb17914117b0.png">

2022-12-14 11:50 UTC, dated approved these changes

2022-12-14 13:14 UTC, merged