[wip] migration step1 metamask
ArdentHQ/arkvault pull request #274
Opened 2022-12-15 22:41 UTC by alfonsobries

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2022-12-16 21:20 UTC, dated commented on src/domains/migration/components/MigrationConnectStep/MigrationConnectStep.tsx
> +	</button>
```suggestion
	<button type="button" className="group relative overflow-hidden rounded-lg bg-gradient-to-r from-[#FFDB80] to-theme-warning-800">
		<span className="absolute inset-0 bg-gradient-to-r from-theme-warning-200 to-theme-navy-500 opacity-0 transition-all duration-200 ease-in-out group-hover:opacity-100" />

		<div className="relative flex space-x-2 py-3.5 px-5">
			<MetamaskLogo />
			<span className="font-semibold text-white">{children}</span>
		</div>
	</button>
```

2022-12-16 21:20 UTC, dated commented on src/domains/migration/i18n.ts
> +							"In order to complete the Migration, you must first install MetaMask. Learn more in our <linkMigrationGuide>Migration Guide.</linkMigrationGuide>",
```suggestion
							"In order to complete the Migration, you must first install MetaMask. Learn more in our <linkMigrationGuide>Migration Guide</linkMigrationGuide>.",
```

2022-12-16 21:20 UTC, dated commented on src/domains/migration/components/MigrationConnectStep/MigrationConnectStep.tsx
> +								<Amount ticker="ARK" value={-TRANSACTION_FEE} showSign />
```suggestion
								<Amount ticker="ARK" value={TRANSACTION_FEE * -1} showSign isNegative />
```

2023-01-03 10:03 UTC, samharperpittam requested changes
The `Polygon Migration Address` field should be a different colour when blurred making the text easier to read. It's more noticeable in dark mode but also an issue in light mode.

Design
<img width="704" alt="image" src="https://user-images.githubusercontent.com/44671015/210335820-b7972822-9b6c-4f4e-9529-53fb311be7e3.png">

Imp
<img width="672" alt="image" src="https://user-images.githubusercontent.com/44671015/210335869-27badea3-5847-4e42-ad7d-18bd8f26b8cb.png">

2023-01-03 10:09 UTC, samharperpittam requested changes
On mobile (375) we should remove the border around the content which will give us more space. See the images below

Des
<img width="393" alt="image" src="https://user-images.githubusercontent.com/44671015/210336671-3082de18-0b64-4792-8275-b5b93894857f.png">


Imp
<img width="431" alt="image" src="https://user-images.githubusercontent.com/44671015/210336721-f5addfd2-f162-4a84-bf40-e53c9790814d.png">

Also on mobile the text should read `In order to complete the Migration, you must first install the MetaMask mobile app or use a Web3-compatible browser. Learn more in our Migration Guide.`

2023-01-03 11:10 UTC, samharperpittam approved these changes

2023-01-03 11:50 UTC, samharperpittam approved these changes

2023-01-03 11:55 UTC, dated approved these changes

2023-01-03 12:05 UTC, merged