feat: metamask mobile handling
ArdentHQ/arkvault pull request #278
Opened 2023-01-03 23:15 UTC by alfonsobries

## Summary

Closes https://app.clickup.com/t/39xfauf

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-01-04 08:49 UTC, samharperpittam requested changes
@alfonsobries  - small issue i've noticed with this.

When connected to Vault using the browser in my Metamask Mobile Application, if I'm connected to a wallet on the Polygon network and then switch to one of the test networks, the error message that i'm on the incorrect network doesn't appear. However, it does when changing to Ethereum mainnet. 

- Open Metamask Mobile App
- Go to Browser
- Visit this Vercel URL
- Change network to Polygon and connect wallet
- Switch network to Kovan Test Network
- No error message displayed.

2023-01-04 17:15 UTC, alfonsobries commented
@samharperpittam fixed ✅

2023-01-05 10:01 UTC, samharperpittam approved these changes

2023-01-05 11:36 UTC, merged

2023-01-05 11:37 UTC, ItsANameToo commented
ah this one was waiting on another PR :colbert: