feat: implement `MigrationReviewStep`
ArdentHQ/arkvault pull request #280
Opened 2023-01-04 14:28 UTC by goga-m

## Summary

Closes https://app.clickup.com/t/39xfaxy

## Checklist

-   [x] My changes look good in both light AND dark mode
-   [x] The change is not hardcoded to a single network, but has multi-asset in mind
-   [x] I checked my changes for obvious issues, debug statements and commented code
-   [x] Documentation _(if necessary)_
-   [x] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-01-05 12:52 UTC, samharperpittam requested changes
Missing background on this icon

Design
<img width="132" alt="image" src="https://user-images.githubusercontent.com/44671015/210784410-6c86b4a2-d355-45f9-a568-470b1120e74b.png">

Imp
<img width="109" alt="image" src="https://user-images.githubusercontent.com/44671015/210784395-d7bed5b7-1c8e-42a4-8b4b-4127aac19d25.png">

2023-01-05 13:00 UTC, samharperpittam requested changes
Button should read "Back" instead of "Cancel"

Design
<img width="271" alt="image" src="https://user-images.githubusercontent.com/44671015/210785737-89fffe24-e032-4ff8-bf77-6aeee13e020b.png">

2023-01-05 13:02 UTC, samharperpittam requested changes
Should be 12px between "Amount Migrated" and the value. Looks a bit less than that atm.

Design
<img width="569" alt="image" src="https://user-images.githubusercontent.com/44671015/210786220-8c73d483-cdf4-4640-9e62-45d28b7e4db1.png">

2023-01-05 13:10 UTC, samharperpittam requested changes
This icon should be `gray-200` in dark mode

<img width="128" alt="image" src="https://user-images.githubusercontent.com/44671015/210787561-9e4638a5-97aa-43ac-b1d0-8a4d6b5e2880.png">

2023-01-05 13:13 UTC, samharperpittam requested changes
Completed icon missing background.

Design
<img width="86" alt="image" src="https://user-images.githubusercontent.com/44671015/210788141-b31bec39-7989-43a9-bcb0-035dd07eae82.png">

Imp
<img width="70" alt="image" src="https://user-images.githubusercontent.com/44671015/210788188-12ed58f5-f3d7-4e15-9a88-37a7efc06ced.png">

2023-01-05 13:19 UTC, samharperpittam requested changes
640 & 375. The content is too wide. Should be 32px of padding around the border of content.

The border is currently within the padding as shown here:
<img width="377" alt="image" src="https://user-images.githubusercontent.com/44671015/210789327-c46b90f1-c185-4034-b7cc-8876420649ce.png">

2023-01-05 13:21 UTC, samharperpittam requested changes
375 - May need more truncation of the wallet address. Icon currently overlaps the text.

Des
<img width="286" alt="image" src="https://user-images.githubusercontent.com/44671015/210789596-c4e568a1-7181-43f1-8a3f-8d34ab782f9e.png">

Imp
<img width="368" alt="image" src="https://user-images.githubusercontent.com/44671015/210789580-31ade51f-e747-412b-9305-a8860124fc85.png">

2023-01-05 13:21 UTC, dated commented on src/domains/migration/components/MigrationReviewStep/MigrationReviewStep.blocks.tsx
> +			<Icon name="DoubleArrowDown" size="lg" />
I think we already have that icon as `Received`

2023-01-05 14:30 UTC, dated commented
> Completed icon missing background.
> 
> Design <img alt="image" width="86" src="https://user-images.githubusercontent.com/44671015/210788141-b31bec39-7989-43a9-bcb0-035dd07eae82.png">
> 
> Imp <img alt="image" width="70" src="https://user-images.githubusercontent.com/44671015/210788188-12ed58f5-f3d7-4e15-9a88-37a7efc06ced.png">

fixed in https://github.com/ArdentHQ/arkvault/pull/282

2023-01-06 09:11 UTC, goga-m commented
@samharperpittam @dated fixed the issues.

2023-01-06 12:28 UTC, ItsANameToo commented
conflicts @goga-m

2023-01-06 15:25 UTC, ItsANameToo approved these changes

2023-01-06 15:25 UTC, merged