feat: implement `MigrationSuccessStep`
ArdentHQ/arkvault pull request #282
Opened 2023-01-04 20:32 UTC by dated

## Summary

https://app.clickup.com/t/39xfbht

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-01-05 14:17 UTC, samharperpittam requested changes
Pretty minor remark but the 5th step is missing a tick

Des
<img width="323" alt="image" src="https://user-images.githubusercontent.com/44671015/210800742-8ca48af6-d310-45f6-a6e2-9966a554ea6c.png">

Imp
<img width="347" alt="image" src="https://user-images.githubusercontent.com/44671015/210800789-8802ed7b-52ae-4a63-9e80-4276e8d9d698.png">

I've mentioned the background colour on the `MigrationReview` PR so should get handled there.

2023-01-05 14:30 UTC, dated commented
fixed in [3fc3d1d](https://github.com/ArdentHQ/arkvault/pull/282/commits/3fc3d1d6ce5a8c4f775e004994c9338bbdcb90a1) @samharperpittam

2023-01-06 09:17 UTC, goga-m approved these changes

2023-01-06 09:55 UTC, samharperpittam approved these changes
Approved but contains some of the issues raised on the `migrationreview` PR

2023-01-06 12:27 UTC, merged