feat: implement `MigrationAuthenticationStep`
ArdentHQ/arkvault pull request #285
Opened 2023-01-05 17:54 UTC by goga-m

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-01-09 15:37 UTC, dated requested changes

2023-01-09 15:37 UTC, dated commented on src/domains/migration/components/MigrationAuthenticationStep/MigrationAuthenticationStep.tsx
> +				<div className="px-4 pt-4">
```suggestion
				<div className="px-5 pt-5">
```

2023-01-09 15:37 UTC, dated commented on src/domains/migration/pages/MigrationAdd/MigrationAdd.tsx
> +						<TabPanel tabId={Step.Authenticate}>
```suggestion

						<TabPanel tabId={Step.Authenticate}>
```

2023-01-10 09:03 UTC, ItsANameToo approved these changes

2023-01-10 09:03 UTC, merged