feat: implement pagination in migrations table
ArdentHQ/arkvault pull request #336
Opened 2023-01-24 16:13 UTC by goga-m

## Summary
Closes https://app.clickup.com/t/86775vn2q

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-01-24 16:42 UTC, samharperpittam requested changes
Comments left on Slack in relation to:
- View More button sometimes not populating additional transactions
- View state persists resulting in a useless "View More" button

2023-01-25 08:35 UTC, goga-m commented
@samharperpittam the pagination should be persistent now, and also adjusted the sorting of the migration transactions list so that it wouldn't change/hide transactions list when you cilck "view more". Let me know if you still see issues. Ty!

2023-01-25 11:59 UTC, ItsANameToo commented
conflicts @goga-m

2023-01-25 13:57 UTC, goga-m commented
The functionality is affected after the merge conflicts. Will move this to draft and re-open once it's working

2023-01-26 11:10 UTC, samharperpittam submitted a review, later dismissed

2023-01-26 11:52 UTC, ItsANameToo commented on src/domains/migration/hooks/use-migration-transactions.ts
> +	const limit = 10;
this limit needs to be applied to the API call, now you slice an array with 100 values and leave 90 out from the UI and when paginating you request another 100, etc

2023-01-26 11:55 UTC, ItsANameToo commented
failing test issue + pagination issue, see slack

2023-01-26 17:11 UTC, ItsANameToo approved these changes

2023-01-26 17:11 UTC, merged