[wip] merge migrations transactions into the context
ArdentHQ/arkvault pull request #360
Opened 2023-01-31 23:28 UTC by alfonsobries

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2023-02-03 10:21 UTC, samharperpittam requested changes
@alfonsobries - I created a new profile and imported a wallet with valid migration transaction but none of the transactions are showing on the overview page anymore.

Wallet page
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/44671015/216575578-efd0308f-e5b4-4db7-9b0d-f513ae3a781a.png">


Overview Page
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/44671015/216575619-8ee432e8-ab6a-4c70-9d7b-bdb66d350efc.png">


- Create Profile
-  Import the following wallet `D9QAsb7YUxGuuQGihz4GKwsCYn8oLw8sT5`
- Go to overview page
- Empty

2023-02-03 21:29 UTC, alfonsobries commented
@samharperpittam can be tested again

2023-02-06 09:47 UTC, samharperpittam approved these changes

2023-02-06 12:08 UTC, ItsANameToo approved these changes

2023-02-06 12:08 UTC, merged