refactor: ledger address list
ArdentHQ/arkvault pull request #610
Opened 2024-08-13 01:52 UTC by patricio0312rev

# [[ledger] adjust address list](https://app.clickup.com/t/86dtzqmpm)

## Summary

- Depends on #609 
- `Address` component has been refactored.
- Icons and translation files have been updated.

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-08-14 04:05 UTC, patricio0312rev commented on .github/workflows/test.yml
> +                  COVERAGE_THRESHOLD_LINES: 99.75
Due to the components being refactored, this line needed to be updated. The lines missing tests are the same as before the PR 🤔

2024-08-14 09:12 UTC, samharperpittam requested changes
Minor issue but the divider line within the table header shouldn't exist.

Design
![image](https://github.com/user-attachments/assets/3ecd5eff-2c99-409c-9f08-109088ca821b)

Implementation
![image](https://github.com/user-attachments/assets/baabf4d5-990b-4b19-b321-c8182fee5837)

2024-08-14 16:57 UTC, patricio0312rev commented on src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.blocks.test.tsx
> +		expect(container).toMatchSnapshot();
But here it is necessary, since I am making sure it is rendering correctly 🤔

2024-08-14 17:03 UTC, patricio0312rev commented
@samharperpittam @shahin-hq PR should be ready to review again ✅

2024-08-15 08:42 UTC, shahin-hq commented on src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.blocks.test.tsx
> +		expect(container).toMatchSnapshot();
I can see you've found the right way, good job :)

2024-08-15 08:45 UTC, shahin-hq commented on src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.blocks.test.tsx
> +		expect(container).toMatchSnapshot();
Thanks for the fix!

2024-08-15 11:04 UTC, samharperpittam approved these changes

2024-08-15 15:53 UTC, merged