refactor: adjust exchange overview table
ArdentHQ/arkvault pull request #621
Opened 2024-08-22 04:40 UTC by patricio0312rev

# [[exchanges] adjust overview table](https://app.clickup.com/t/86du01z83)

## Summary

- Exchange overview table view has been refactor to match the new designs.

<img width="1455" alt="image" src="https://github.com/user-attachments/assets/f856475d-a492-4193-bf4b-07841fa617bf">

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-08-22 09:37 UTC, shahin-hq commented
Hey @patricio0312rev, I know it is not ready to review yet but there is a thing you could easily fix:

![image](https://github.com/user-attachments/assets/2907e337-953c-4538-b7e0-93d24b183ffa)

notice how the line between rows are not reaching to the ends, you can fix easily by adding `with-x-padding` class to the parent of the `table` and `relative` class to `tr`s

https://github.com/ArdentHQ/arkvault/pull/618/files#diff-77d4b4f04e431b43ffaa86e16043e4961c791f30f2cfd5576e44c0df3c3a52aaR63

2024-08-23 13:03 UTC, patricio0312rev commented on package.json
> +		"tailwind-merge": "^2.5.2",
I was having trouble with the `css` and `tw` props not overwriting all the class names in the styled component for the Table cell. Decided to directly install `twMerge` and refactor this component as a simple react component with twMerge handling their overwritten class names.

2024-08-23 13:07 UTC, patricio0312rev commented on src/styles/base.css
> +	@apply content-[''] w-6 block bg-theme-background h-full absolute left-0
When using a tooltip on the first cell of a column, the white padding line was always being placed in the middle (might be due to the floating position of the tooltip), causing the padding not to appear. However, using the full height of the cell fixed this.

2024-08-23 14:27 UTC, samharperpittam requested changes
Minor point but the "Time Ago" column text should be semi-bold to match the exchange column.

Design
![image](https://github.com/user-attachments/assets/371af5f2-b9e4-4b6e-bc54-2a126b3bc4ca)

Implementation
![image](https://github.com/user-attachments/assets/b4c81d3b-247f-4728-b6ea-b1ee0d5d209e)

2024-08-23 14:35 UTC, samharperpittam requested changes
Also I think the tables are too big in height.

Designs should 12px of padding above and below the value 
![image](https://github.com/user-attachments/assets/b616f6ad-80bf-4941-9c53-8f6c2c199703)

However it looks like the table in implementation has 24px of padding above and below due to the additional space identified with an arrow here:
![image](https://github.com/user-attachments/assets/e1019832-5f07-4223-a00d-a17f3172abb3)

2024-08-27 10:05 UTC, ItsANameToo requested changes

2024-08-27 10:05 UTC, ItsANameToo commented on src/app/components/Amount/AmountLabel.tsx
> +		hintClassName = "bg-[#A56D4C] dark:bg-[#AA6868] text-white";
do these purposely differ from the color options in the palette?

2024-08-27 10:05 UTC, ItsANameToo commented on src/app/components/Label/Label.styles.tsx
> +			tw`text-[#A56D4C] bg-[#FBEED6] dark:border dark:text-[#F39B9B] dark:bg-transparent dark:border-[#AA6868]`,
same question here, not a fan of hex codes for colors 🤔 if they are different in the design, is there any color in the palette close enough to use for it instead?

2024-08-27 10:23 UTC, ItsANameToo commented on .github/workflows/test.yml
> +                  COVERAGE_THRESHOLD_BRANCHES: 99.66
@goga-m see my answer here https://github.com/ArdentHQ/arkvault/pull/618#discussion_r1726607337

2024-08-28 13:36 UTC, ItsANameToo approved these changes

2024-08-28 14:47 UTC, samharperpittam approved these changes

2024-08-28 14:55 UTC, ItsANameToo commented
more conflicts @patricio0312rev 😂

2024-08-28 15:23 UTC, merged