refactor: adjust delegates list page
ArdentHQ/arkvault pull request #632
Opened 2024-08-29 12:16 UTC by shahin-hq

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-09-03 12:38 UTC, shahin-hq commented
> Is the "Validated name" correct here or an oversight from the designs? Shouldn't it be delegate, considering that we are in develop branch? ![2024-09-03-123839_402x156_scrot](https://private-user-images.githubusercontent.com/22020168/363949294-f4951ba4-d06a-4a37-83b1-0b289a133967.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzNjczMjUsIm5iZiI6MTcyNTM2NzAyNSwicGF0aCI6Ii8yMjAyMDE2OC8zNjM5NDkyOTQtZjQ5NTFiYTQtZDA2YS00YTM3LTgzYjEtMGIyODlhMTMzOTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAzVDEyMzcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwN2Q0MmFlZWNjMzA3ZTVjNmFjNDBlYjlmMGM4ZWVjZmQ5OWMzN2YzMDUxNmZhNzFhMTY1MGYzODVlNTM2ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lLwgCa9ozDwXifUToy0Vf9zbjyfGrckSxcvsSiP2iDI)

https://www.figma.com/design/o6b1tEMOdUtHv7ijVs6pMX/ARKVault?node-id=13929-58239&node-type=TEXT&m=dev

it is `validated name` here too, will ask Oleg to clarify

![image](https://github.com/user-attachments/assets/bd59094f-e032-4394-b74b-d9d1aa2ed92b)

2024-09-03 12:49 UTC, ItsANameToo commented
> > Is the "Validated name" correct here or an oversight from the designs? Shouldn't it be delegate, considering that we are 

"validated" is wrong either way, it should be `Validator Name`. In this case since it targets develop it will need to be `Delegate Name`. General rule: when it is about delegates/validators mind the branch you work on to determine the correct word, and make it configurable to handle the Mainsail network (similar to what is done in other areas where it swaps between delegate/validator depending on network).

2024-09-04 09:10 UTC, samharperpittam requested changes
Looking good. Only minor issue I can find is that the padding shown in the image below should be 24px

![image](https://github.com/user-attachments/assets/5f45902a-b588-4598-b59c-f93912dc9961)


Design
![image](https://github.com/user-attachments/assets/ef8d2d67-55b1-43db-b06c-caffe0545596)

2024-09-04 13:59 UTC, shahin-hq commented on src/domains/vote/components/AddressTable/AddressRow/AddressRowMobile.test.tsx
> +		const containerDiv = container.querySelector("tr td > div") as HTMLDivElement;
Thanks. Fixed.

2024-09-04 14:41 UTC, samharperpittam approved these changes

2024-09-04 14:55 UTC, merged