fix: adjustments on wallet list component
ArdentHQ/arkvault pull request #661
Opened 2024-09-20 10:23 UTC by goga-m

## Summary
Closes https://app.clickup.com/t/86dupz4e4
Closes https://app.clickup.com/t/86dupzb1v

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-09-20 13:37 UTC, shahin-hq commented on src/domains/wallet/components/WalletsList/WalletsList.tsx
> +								className="with-x-padding after:mx-[0.15rem] after:block after:h-[5px] after:rounded-b-lg after:bg-theme-primary-100 after:content-[''] after:dark:bg-theme-secondary-800"
Have you tried this trick for the border bottom? https://github.com/ArdentHQ/arkvault/blob/c7f12e38a357c8caf12134e462a10a3c766a990d/src/domains/vote/components/AddressTable/AddressTable.tsx#L153

2024-09-20 14:00 UTC, samharperpittam requested changes
Dropdowns are looking good.

In relation to the border, in a scenario where the "Show All" button is displayed, the table shouldn't contain the border. 

Design
![image](https://github.com/user-attachments/assets/c5ec4bf3-de3c-47f8-b223-f7cc72a84b85)

Implementation
![image](https://github.com/user-attachments/assets/eb80b45b-afc2-4bf9-a099-6eebb814b516)

2024-09-20 15:16 UTC, shahin-hq commented on src/domains/wallet/components/WalletsList/WalletsList.tsx
> +								className="with-x-padding after:mx-[0.15rem] after:block after:h-[5px] after:rounded-b-lg after:bg-theme-primary-100 after:content-[''] after:dark:bg-theme-secondary-800"
@goga-m Am I missing something?

![image](https://github.com/user-attachments/assets/a39f7472-0c60-4962-81cb-476f4fa279ca)

2024-09-23 09:29 UTC, samharperpittam approved these changes

2024-09-25 03:59 UTC, patricio0312rev approved these changes
🔥 🔥

2024-09-25 10:34 UTC, merged