refactor: adjust designs on musig flow screens
ArdentHQ/arkvault pull request #667
Opened 2024-09-24 15:45 UTC by goga-m

Closes https://app.clickup.com/t/86dum87nr 

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-09-27 12:41 UTC, samharperpittam requested changes
At 640, the signature table doesn't contain a border
![image](https://github.com/user-attachments/assets/9147acf4-d0b1-4afb-b6d4-dfc3dd8ae0f3)

Design
![image](https://github.com/user-attachments/assets/634ca870-944d-4d65-98d6-7a6bc0cce86b)

2024-09-27 12:45 UTC, samharperpittam requested changes
At 320 there's a couple of issues

- Copy button isn't styled correctly
![image](https://github.com/user-attachments/assets/f15008fa-a831-46c0-8c5a-fe5fa3556dcf)

- Address font size too large
![image](https://github.com/user-attachments/assets/0b2176ca-bda1-4080-b65e-9e866ce83b1b)

- Alert styling is too large when compared with designs
![image](https://github.com/user-attachments/assets/35ba1327-3843-49f2-b516-d1dd51a5fcc8)

2024-10-01 08:18 UTC, samharperpittam approved these changes

2024-10-01 08:25 UTC, ItsANameToo approved these changes

2024-10-02 08:15 UTC, merged