refactor: add wallets pagination
ArdentHQ/arkvault pull request #700
Opened 2024-10-11 13:42 UTC by shahin-hq

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-10-14 10:26 UTC, samharperpittam requested changes
Should be 8px of padding between the number value and the chevron
![image](https://github.com/user-attachments/assets/6cce8e12-70d6-40ac-972b-a1d55c794aa1)


Also the chevron doesn't match the design

Design
![image](https://github.com/user-attachments/assets/bdb79f93-1d73-42c6-914b-9c650ce7ab1b)

Imp
![image](https://github.com/user-attachments/assets/a92df1b0-a5e0-4f2f-bcb7-fe46b9b33270)

2024-10-14 10:50 UTC, samharperpittam requested changes
640
![image](https://github.com/user-attachments/assets/bb97f57a-6621-457f-bdb7-e095c57230b3)

2024-10-14 12:18 UTC, shahin-hq commented
@samharperpittam fixed alignment issue, please check again

2024-10-14 15:42 UTC, samharperpittam approved these changes

2024-10-15 09:23 UTC, ItsANameToo approved these changes

2024-10-15 09:23 UTC, merged