fix: input font size
ArdentHQ/arkvault pull request #729
Opened 2024-10-15 13:32 UTC by shahin-hq

## Summary
Closes: https://app.clickup.com/t/86dux5wy9

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-10-15 14:32 UTC, samharperpittam requested changes
Couple of issues with this.

Sender input is still 16px
![image](https://github.com/user-attachments/assets/ada7bf60-1337-40e1-a98a-329896de1d40)

---

Transaction Fee text seems to have an issue on this PR. Seems fine on demo. 
![image](https://github.com/user-attachments/assets/0977cfc6-f323-4bc4-8116-b4a64f24480e)

---

Can we also change the Scan QR Code text to 14px to please

![image](https://github.com/user-attachments/assets/4aed14da-db38-4c0a-83f2-1feacc24fce1)

2024-10-15 15:21 UTC, samharperpittam approved these changes

2024-10-16 09:01 UTC, ItsANameToo commented on src/app/components/Header/HeaderSearchInput/__snapshots__/HeaderSearchInput.test.tsx.snap
> +              class="no-ligatures w-full border-none !text-sm sm:!text-base css-1vs1awz"
what is causing the need for `!` here? same question to the other occurences

2024-10-16 09:22 UTC, ItsANameToo approved these changes

2024-10-16 09:22 UTC, ItsANameToo commented on src/app/components/Header/HeaderSearchInput/__snapshots__/HeaderSearchInput.test.tsx.snap
> +              class="no-ligatures w-full border-none !text-sm sm:!text-base css-1vs1awz"
twin.macro's base styles cause this

2024-10-16 09:46 UTC, merged