fix: move `send all` button in mobile
ArdentHQ/arkvault pull request #737
Opened 2024-10-16 10:15 UTC by shahin-hq

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-10-18 08:06 UTC, ItsANameToo commented
also some failing e2e @shahin-hq

2024-10-18 09:29 UTC, samharperpittam requested changes
Can we remove the "Available" text and see if it fits okay so the Send All text is on a single line please?
![image](https://github.com/user-attachments/assets/edf28fd3-2f7a-4b7b-ad60-ca235a0c8644)

Design
![image](https://github.com/user-attachments/assets/ab9b847b-c9dc-4812-acba-f87d8d951332)

2024-10-18 09:58 UTC, shahin-hq commented on src/domains/transaction/components/AddRecipient/AddRecipient.tsx
> +											<Amount value={+remainingNetBalance} ticker={ticker} showTicker={false} />)
Fixed. He has parenthesis in the example, so I kept them

2024-10-18 11:21 UTC, shahin-hq commented on src/domains/transaction/components/AddRecipient/AddRecipient.tsx
> +											<Amount value={+remainingNetBalance} ticker={ticker} showTicker={false} />)
Should be good now

2024-10-21 09:51 UTC, samharperpittam requested changes
Can we make the "Send all" text Dark-Navy-Blue - 600 in dark mode please.

2024-10-21 15:13 UTC, samharperpittam approved these changes

2024-10-21 15:55 UTC, merged