fix: display delegate information in summary step for vote txs
ArdentHQ/arkvault pull request #749
Opened 2024-10-18 14:09 UTC by goga-m

## Summary
Closes https://app.clickup.com/t/86dux5j0y

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-10-21 08:24 UTC, samharperpittam approved these changes

2024-10-21 09:58 UTC, ItsANameToo requested changes
some comments and failing tests @goga-m

2024-10-21 09:58 UTC, ItsANameToo commented on src/domains/transaction/hooks/use-transaction-voting-wallets.ts
> +		votes: votes.map((publikKey: string) => publikKey.replace(/^[+-]+/, "")),
```suggestion
		unvotes: unvotes.map((publicKey: string) => publicKey.replace(/^[+-]+/, "")),
		votes: votes.map((publicKey: string) => publicKey.replace(/^[+-]+/, "")),
```

2024-10-21 09:58 UTC, ItsANameToo commented on src/domains/transaction/hooks/use-transaction-voting-wallets.ts
> +	const unvotes = data?.asset?.unvotes ?? [];
maybe turn this into two helpers, one for confirmed (using the `votes` and `unvotes` methods) and one for the signed tx that uses the raw asset? that will make it easier to follow why these checks are done and different data is accessed

2024-10-21 09:58 UTC, ItsANameToo commented on src/domains/transaction/hooks/use-transaction-voting-wallets.ts
> + * @TODO: This can be handled in SDK to retrieve voting and unvoting public keys (or generally the asset data)
can you add a discussion card for this to clickup please

2024-10-21 15:42 UTC, ItsANameToo approved these changes

2024-10-21 15:42 UTC, merged

2024-10-23 10:21 UTC, ItsANameToo commented
also https://app.clickup.com/t/86duyv9rd