refactor: adjust ledger loading screen
ArdentHQ/arkvault pull request #770
Opened 2024-10-24 10:52 UTC by goga-m

## Summary
Closes https://app.clickup.com/t/86duu4enr 

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-10-24 14:34 UTC, samharperpittam requested changes
Got an issue in Light mode

![image](https://github.com/user-attachments/assets/36d1dcdc-3497-4607-82e1-4941494ad8c7)

2024-10-25 10:16 UTC, samharperpittam requested changes
The spinner should be 20x20 
![image](https://github.com/user-attachments/assets/d7e16123-a5b8-41dd-9b7c-0c3450de07b3)

Seems to be a bit bigger?

2024-10-25 10:59 UTC, samharperpittam approved these changes

2024-10-25 11:53 UTC, ItsANameToo approved these changes

2024-10-25 11:53 UTC, merged