refactor: add BLS public key for validator registration
ArdentHQ/arkvault pull request #827
Opened 2024-11-20 10:50 UTC by shahin-hq

## Summary

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-11-20 16:10 UTC, ItsANameToo requested changes

2024-11-20 16:10 UTC, ItsANameToo commented on src/domains/transaction/validations/ValidatorRegistration.ts
> +			true,
add validation, psdk already exposes it

2024-11-20 16:10 UTC, ItsANameToo commented on src/domains/transaction/validations/ValidatorRegistration.test.tsx
> +	// it("should validate BLS public key", async () => {
enable the test

2024-11-21 19:59 UTC, shahin-hq commented on src/app/App.test.tsx
> -		const memoryPasswordMock = vi.spyOn(env.profiles().last().password(), "get").mockImplementation(() => {
Since I added a new profile for Mainsail the given profile is no longer the `last` one

2024-11-21 20:48 UTC, ItsANameToo approved these changes

2024-11-21 20:48 UTC, merged