fix: properly display contract label in transaction rows
ArdentHQ/arkvault pull request #840
Opened 2024-12-03 14:07 UTC by goga-m

## Summary
Closes https://app.clickup.com/t/86dvabpvb

## Checklist

-   [ ] My changes look good in both light AND dark mode
-   [ ] The change is not hardcoded to a single network, but has multi-asset in mind
-   [ ] I checked my changes for obvious issues, debug statements and commented code
-   [ ] Documentation _(if necessary)_
-   [ ] Tests _(if necessary)_
-   [ ] Ready to be merged

2024-12-03 14:43 UTC, ItsANameToo requested changes

2024-12-03 14:43 UTC, ItsANameToo commented on src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAddressing.tsx
> +			delegates[transaction.isVote() || transaction.isVoteCombination() ? "votes" : "unvotes"][0]?.username();
did you test this? 🤔

2024-12-04 12:31 UTC, samharperpittam approved these changes

2024-12-04 15:25 UTC, ItsANameToo approved these changes

2024-12-04 15:26 UTC, merged